/**
 * The service worker's URL parsing, checked against routes Python produces.
 *
 * This is a platform boundary rather than an algorithm: if the two sides
 * disagree on where a route ends and a chunk key begins, the only symptom is
 * blank tiles in the viewer. `fixtures.json` is generated by
 * `tests/browser/dump_route_fixtures.py`, so the expectations here come from
 * the real Python implementation.
 *
 *   node --test tests/browser/routes.test.mjs
 */

import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");

const require = createRequire(import.meta.url);
const routes = require(join(repoRoot, "docs", "browser", "routes.js"));

const fixtures = JSON.parse(readFileSync(join(here, "fixtures.json"), "utf8"));

test("requests outside the service worker prefix are ignored", () => {
  assert.equal(routes.parseRequest("/multiview-stitcher/browser/app.js"), null);
  assert.equal(routes.parseRequest("/neuroglancer/index.html"), null);
});

test("the prefix is matched anywhere, so sub-path deployments work", () => {
  for (const base of ["", "/multiview-stitcher", "/multiview-stitcher/main/browser"]) {
    assert.deepEqual(routes.parseRequest(`${base}/__mvs__/fs/abc/x/.zattrs`), {
      kind: "fs",
      path: "abc/x/.zattrs",
    });
  }
});

test("file paths split into a mount and a relative path", () => {
  assert.deepEqual(routes.parseFilePath("a1b2c3d4/tile_0.ome.zarr/0/0/0/0/0"), {
    mount: "a1b2c3d4",
    path: "tile_0.ome.zarr/0/0/0/0/0",
  });
  assert.equal(routes.parseFilePath("no-slash"), null);
});

test("virtual OME-Zarr paths split at the route suffix", () => {
  for (const { route, key, path } of fixtures.zarr_requests) {
    assert.deepEqual(
      routes.parseZarrPath(path),
      { route, key },
      `parsing ${path}`,
    );
  }
});

test("routes generated by Python round-trip through the full request path", () => {
  for (const { route, key, path } of fixtures.zarr_requests) {
    const request = routes.parseRequest(`/app/__mvs__/zarr/${path}`);
    assert.equal(request.kind, "zarr");

    const parsed = routes.parseZarrPath(request.path);
    assert.equal(parsed.route, route);
    assert.equal(parsed.key, key);
  }
});

test("a route from a retired generation is still parseable", () => {
  // The service worker must forward it so Python can answer 404; dropping it
  // here would look like a network error instead of an invalidated cache.
  const parsed = routes.parseZarrPath(fixtures.stale_request.path);
  assert.equal(parsed.route, fixtures.stale_request.route);
});

test("the viewer iframe is not treated as an app page", () => {
  // The Neuroglancer iframe is a window client of the same scope, but it has
  // no handler for the service worker's messages: sending it a chunk request
  // means waiting for a reply that never arrives, which stalls the viewer
  // exactly when it is fetching most.
  const scope = "http://localhost:8000/browser/";

  assert.equal(routes.isAppPage(`${scope}`, scope), true);
  assert.equal(routes.isAppPage(`${scope}index.html`, scope), true);
  assert.equal(routes.isAppPage(`${scope}index.html?x=1`, scope), true);

  assert.equal(routes.isAppPage(`${scope}neuroglancer/index.html`, scope), false);
  assert.equal(
    routes.isAppPage(`${scope}neuroglancer/index.html#!%7B%7D`, scope),
    false,
  );
});

test("app pages are recognised under a sub-path deployment", () => {
  const scope = "https://example.org/multiview-stitcher/main/browser/";

  assert.equal(routes.isAppPage(`${scope}index.html`, scope), true);
  assert.equal(routes.isAppPage(`${scope}neuroglancer/index.html`, scope), false);
});

test("metadata keys are told apart from chunk data", () => {
  // Metadata must be answered by the worker that owns the session; a layer
  // whose .zattrs fails to load has nothing to render, however well the chunk
  // path works.
  for (const key of [".zattrs", ".zgroup", ".zmetadata", "zarr.json", "0/.zarray", "1/.zattrs"]) {
    assert.equal(routes.isMetadataKey(key), true, key);
  }

  for (const key of ["0/0/0/0/0", "1/0/0/3/2", "0/0.0.0.0", ""]) {
    assert.equal(routes.isMetadataKey(key), false, key);
  }
});

test("the wheel URL changes when the wheel does", async () => {
  // A rebuild of the same commit produces an identically named wheel, and
  // micropip fetches it from inside a worker - where a page reload does not
  // bypass the HTTP cache. Only a changing URL keeps the Python runtime in
  // step with the JavaScript.
  const { readFileSync } = await import("node:fs");
  const manifest = JSON.parse(
    readFileSync(join(repoRoot, "docs", "browser", "packages", "manifest.json"), "utf8"),
  );

  assert.ok(manifest.sha256, "the manifest must carry a wheel checksum");
  assert.equal(manifest.build, manifest.sha256.slice(0, 12));

  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  assert.match(app, /packages\/\$\{manifest\.wheel\}\?v=\$\{build\}/);
  // Worker scripts are loaded the same way and need the same treatment.
  for (const worker of ["fs-worker.js", "session-worker.js", "compute-worker.js"]) {
    assert.match(
      app,
      new RegExp(`${worker.replace(".", "\\.")}\\?v=`),
      `${worker} must be cache-busted`,
    );
  }
  assert.match(app, /fetch\("config\.json", noStore\)/);
  assert.match(app, /fetch\("packages\/manifest\.json", noStore\)/);
});

test("a tab owns only the routes of its own session", () => {
  // The service worker asks every open tab and takes the first that does not
  // decline. A tab with no session must decline everything: otherwise it
  // answers for another tab's images out of an empty session, and the tab
  // that actually holds the data is never asked.
  assert.equal(routes.ownsRoute("abc123", "abc123/g2/fused.ome.zarr"), true);
  assert.equal(routes.ownsRoute("abc123", "abc123/g9/view_0.ome.zarr"), true);

  assert.equal(routes.ownsRoute("abc123", "other/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute(null, "abc123/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute(undefined, "abc123/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute("", "abc123/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute("abc123", ""), false);

  // A session id that is a prefix of another must not match it.
  assert.equal(routes.ownsRoute("abc", "abc123/g2/fused.ome.zarr"), false);
});

test("the page loads its own scripts at the build version", async () => {
  // A cached app.js behind a freshly cache-busted wheel means running two
  // halves of different builds, which fails in ways that resemble neither.
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");

  // No unversioned script tags for our own code.
  assert.doesNotMatch(html, /<script src="(routes|app)\.js"><\/script>/);
  assert.match(html, /packages\/manifest\.json", \{ cache: "no-store" \}/);
  assert.match(html, /\$\{src\}\?v=\$\{build\}/);
  for (const src of ["routes.js", "app.js"]) {
    assert.ok(html.includes(`"${src}"`), `${src} must be loaded by the bootstrap`);
  }
});
