/**
 * The service worker's URL parsing, checked against routes Python produces.
 *
 * This is a platform boundary rather than an algorithm: if the two sides
 * disagree on where a route ends and a chunk key begins, the only symptom is
 * blank tiles in the viewer. `fixtures.json` is generated by
 * `tests/browser/dump_route_fixtures.py`, so the expectations here come from
 * the real Python implementation.
 *
 *   node --test tests/browser/routes.test.mjs
 */

import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");

const require = createRequire(import.meta.url);
const routes = require(join(repoRoot, "docs", "browser", "routes.js"));

const fixtures = JSON.parse(readFileSync(join(here, "fixtures.json"), "utf8"));

test("requests outside the service worker prefix are ignored", () => {
  assert.equal(routes.parseRequest("/multiview-stitcher/browser/app.js"), null);
  assert.equal(routes.parseRequest("/neuroglancer/index.html"), null);
});

test("the prefix is matched anywhere, so sub-path deployments work", () => {
  for (const base of ["", "/multiview-stitcher", "/multiview-stitcher/main/browser"]) {
    assert.deepEqual(routes.parseRequest(`${base}/__mvs__/fs/abc/x/.zattrs`), {
      kind: "fs",
      path: "abc/x/.zattrs",
    });
  }
});

test("file paths split into a mount and a relative path", () => {
  assert.deepEqual(routes.parseFilePath("a1b2c3d4/tile_0.ome.zarr/0/0/0/0/0"), {
    mount: "a1b2c3d4",
    path: "tile_0.ome.zarr/0/0/0/0/0",
  });
  assert.equal(routes.parseFilePath("no-slash"), null);
});

test("virtual OME-Zarr paths split at the route suffix", () => {
  for (const { route, key, path } of fixtures.zarr_requests) {
    assert.deepEqual(
      routes.parseZarrPath(path),
      { route, key },
      `parsing ${path}`,
    );
  }
});

test("routes generated by Python round-trip through the full request path", () => {
  for (const { route, key, path } of fixtures.zarr_requests) {
    const request = routes.parseRequest(`/app/__mvs__/zarr/${path}`);
    assert.equal(request.kind, "zarr");

    const parsed = routes.parseZarrPath(request.path);
    assert.equal(parsed.route, route);
    assert.equal(parsed.key, key);
  }
});

test("a route from a retired generation is still parseable", () => {
  // The service worker must forward it so Python can answer 404; dropping it
  // here would look like a network error instead of an invalidated cache.
  const parsed = routes.parseZarrPath(fixtures.stale_request.path);
  assert.equal(parsed.route, fixtures.stale_request.route);
});
