/**
 * The service worker's URL parsing, checked against routes Python produces.
 *
 * This is a platform boundary rather than an algorithm: if the two sides
 * disagree on where a route ends and a chunk key begins, the only symptom is
 * blank tiles in the viewer. `fixtures.json` is generated by
 * `tests/browser/dump_route_fixtures.py`, so the expectations here come from
 * the real Python implementation.
 *
 *   node --test tests/browser/routes.test.mjs
 */

import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");

const require = createRequire(import.meta.url);
const routes = require(join(repoRoot, "docs", "browser", "routes.js"));

const fixtures = JSON.parse(readFileSync(join(here, "fixtures.json"), "utf8"));

test("requests outside the service worker prefix are ignored", () => {
  assert.equal(routes.parseRequest("/multiview-stitcher/browser/app.js"), null);
  assert.equal(routes.parseRequest("/neuroglancer/index.html"), null);
});

test("the prefix is matched anywhere, so sub-path deployments work", () => {
  for (const base of ["", "/multiview-stitcher", "/multiview-stitcher/main/browser"]) {
    assert.deepEqual(routes.parseRequest(`${base}/__mvs__/fs/abc/x/.zattrs`), {
      kind: "fs",
      path: "abc/x/.zattrs",
    });
  }
});

test("file paths split into a mount and a relative path", () => {
  assert.deepEqual(routes.parseFilePath("a1b2c3d4/tile_0.ome.zarr/0/0/0/0/0"), {
    mount: "a1b2c3d4",
    path: "tile_0.ome.zarr/0/0/0/0/0",
  });
  assert.equal(routes.parseFilePath("no-slash"), null);
});

test("virtual OME-Zarr paths split at the route suffix", () => {
  for (const { route, key, path } of fixtures.zarr_requests) {
    assert.deepEqual(
      routes.parseZarrPath(path),
      { route, key },
      `parsing ${path}`,
    );
  }
});

test("routes generated by Python round-trip through the full request path", () => {
  for (const { route, key, path } of fixtures.zarr_requests) {
    const request = routes.parseRequest(`/app/__mvs__/zarr/${path}`);
    assert.equal(request.kind, "zarr");

    const parsed = routes.parseZarrPath(request.path);
    assert.equal(parsed.route, route);
    assert.equal(parsed.key, key);
  }
});

test("a route from a retired generation is still parseable", () => {
  // The service worker must forward it so Python can answer 404; dropping it
  // here would look like a network error instead of an invalidated cache.
  const parsed = routes.parseZarrPath(fixtures.stale_request.path);
  assert.equal(parsed.route, fixtures.stale_request.route);
});

test("the viewer iframe is not treated as an app page", () => {
  // The Neuroglancer iframe is a window client of the same scope, but it has
  // no handler for the service worker's messages: sending it a chunk request
  // means waiting for a reply that never arrives, which stalls the viewer
  // exactly when it is fetching most.
  const scope = "http://localhost:8000/browser/";

  assert.equal(routes.isAppPage(`${scope}`, scope), true);
  assert.equal(routes.isAppPage(`${scope}index.html`, scope), true);
  assert.equal(routes.isAppPage(`${scope}index.html?x=1`, scope), true);

  assert.equal(routes.isAppPage(`${scope}neuroglancer/index.html`, scope), false);
  assert.equal(
    routes.isAppPage(`${scope}neuroglancer/index.html#!%7B%7D`, scope),
    false,
  );
});

test("app pages are recognised under a sub-path deployment", () => {
  const scope = "https://example.org/multiview-stitcher/main/browser/";

  assert.equal(routes.isAppPage(`${scope}index.html`, scope), true);
  assert.equal(routes.isAppPage(`${scope}neuroglancer/index.html`, scope), false);
});

test("metadata keys are told apart from chunk data", () => {
  // Metadata must be answered by the worker that owns the session; a layer
  // whose .zattrs fails to load has nothing to render, however well the chunk
  // path works.
  for (const key of [".zattrs", ".zgroup", ".zmetadata", "zarr.json", "0/.zarray", "1/.zattrs"]) {
    assert.equal(routes.isMetadataKey(key), true, key);
  }

  for (const key of ["0/0/0/0/0", "1/0/0/3/2", "0/0.0.0.0", ""]) {
    assert.equal(routes.isMetadataKey(key), false, key);
  }
});

test("the build id covers the app, not just the wheel", async (t) => {
  // `docs/browser/packages/` holds build output and is not checked in, so a
  // fresh clone - and CI, which builds its wheel elsewhere - has no manifest
  // to read. The assertions that need one are worth keeping, but not at the
  // cost of a failure that says nothing about the code.
  const { existsSync, readFileSync } = await import("node:fs");
  const path = join(repoRoot, "docs", "browser", "packages", "manifest.json");
  if (!existsSync(path)) {
    t.skip("no manifest; run scripts/build_browser_app.py to check this");
    return;
  }

  const manifest = JSON.parse(readFileSync(path, "utf8"));
  assert.ok(manifest.sha256, "the manifest must carry a wheel checksum");

  // An id derived from the wheel alone would not move when only JavaScript
  // changed, leaving every such fix hidden behind the cached copy of the very
  // file it was meant to replace.
  assert.match(manifest.build, /^[0-9a-f]{12}$/);
  assert.notEqual(
    manifest.build,
    manifest.sha256.slice(0, 12),
    "the build id should not be the wheel checksum on its own",
  );
});

test("the wheel URL changes when the wheel does", async () => {
  // A rebuild of the same commit produces an identically named wheel, and
  // micropip fetches it from inside a worker - where a page reload does not
  // bypass the HTTP cache. Only a changing URL keeps the Python runtime in
  // step with the JavaScript.
  const { readFileSync } = await import("node:fs");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  assert.match(app, /packages\/\$\{manifest\.wheel\}\?v=\$\{build\}/);
  // Worker scripts are loaded the same way and need the same treatment.
  for (const worker of ["fs-worker.js", "session-worker.js", "compute-worker.js"]) {
    assert.match(
      app,
      new RegExp(`${worker.replace(".", "\\.")}\\?v=`),
      `${worker} must be cache-busted`,
    );
  }
  assert.match(app, /fetch\("config\.json", noStore\)/);
  assert.match(app, /fetch\("packages\/manifest\.json", noStore\)/);
});

test("a tab owns only the routes of its own session", () => {
  // The service worker asks every open tab and takes the first that does not
  // decline. A tab with no session must decline everything: otherwise it
  // answers for another tab's images out of an empty session, and the tab
  // that actually holds the data is never asked.
  assert.equal(routes.ownsRoute("abc123", "abc123/g2/fused.ome.zarr"), true);
  assert.equal(routes.ownsRoute("abc123", "abc123/g9/view_0.ome.zarr"), true);

  assert.equal(routes.ownsRoute("abc123", "other/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute(null, "abc123/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute(undefined, "abc123/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute("", "abc123/g2/fused.ome.zarr"), false);
  assert.equal(routes.ownsRoute("abc123", ""), false);

  // A session id that is a prefix of another must not match it.
  assert.equal(routes.ownsRoute("abc", "abc123/g2/fused.ome.zarr"), false);
});

test("the page loads its own scripts at the build version", async () => {
  // A cached app.js behind a freshly cache-busted wheel means running two
  // halves of different builds, which fails in ways that resemble neither.
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");

  // No unversioned script tags for our own code.
  assert.doesNotMatch(html, /<script src="(routes|app)\.js"><\/script>/);
  assert.match(html, /packages\/manifest\.json", \{ cache: "no-store" \}/);
  assert.match(html, /\$\{src\}\?v=\$\{build\}/);
  for (const src of ["routes.js", "app.js"]) {
    assert.ok(html.includes(`"${src}"`), `${src} must be loaded by the bootstrap`);
  }
});

test("the page starts its workers eagerly and without blocking", async () => {
  // Booting a Pyodide runtime takes seconds; doing it on the first action
  // makes the whole UI wait for something it already knew it would need.
  const { readFileSync } = await import("node:fs");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  assert.match(app, /function startWorkers\(\)/);
  // Fired at start-up and on every change of the worker count.
  assert.match(app, /select\.addEventListener\("change", \(\) => \{[\s\S]*?startWorkers\(\);/);
  // Not awaited: the promise is only observed to report failure.
  assert.match(app, /pool\s*\n?\s*\.resize\(requested, state\.runtimeConfig\)\s*\n?\s*\.catch\(/);
  // Work still waits for a pool that is still coming up.
  assert.match(app, /await pool\.ready\(\)/);
});

test("dropped folders are claimed before any await", async () => {
  // A DataTransferItemList is only valid during the event; reading it after a
  // yield returns nothing, so every handle must be claimed synchronously.
  const { readFileSync } = await import("node:fs");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  const handler = app.slice(
    app.indexOf('dropzone.addEventListener("drop"'),
    app.indexOf("$(\"#browse\").addEventListener"),
  );

  const claim = handler.indexOf("items.map((item) => item.getAsFileSystemHandle())");
  const firstAwait = handler.indexOf("await ");
  assert.ok(claim > 0, "handles must be claimed from the item list");
  assert.ok(claim < firstAwait, "handles must be claimed before the first await");
  assert.match(handler, /loadDirectories\(directories\)/);
});

test("Neuroglancer is embedded, not framed", async () => {
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  assert.doesNotMatch(html, /<iframe/i, "the viewer must not be an iframe");
  assert.match(html, /<div id="viewer"/);
  // Its stylesheet came with the iframe before; an embedded viewer needs it.
  assert.match(html, /neuroglancer\/neuroglancer\.css/);

  // The app drives a mounted viewer rather than a document location.
  assert.doesNotMatch(app, /contentWindow/);
  assert.doesNotMatch(app, /neuroglancer\/index\.html/);
  assert.match(app, /viewer\.setState\(ngState\)/);
});

test("Neuroglancer-specific code stays in the viewer module", async () => {
  // The point of the module: upgrading the viewer means reading one file.
  const { readFileSync, readdirSync } = await import("node:fs");
  const dir = join(repoRoot, "docs", "browser");

  for (const name of readdirSync(dir).filter((f) => f.endsWith(".js"))) {
    if (name === "viewer.js") continue;
    const source = readFileSync(join(dir, name), "utf8");
    assert.doesNotMatch(
      source,
      /from "\.\/neuroglancer\//,
      `${name} must not import neuroglancer directly`,
    );
  }

  const viewer = readFileSync(join(dir, "viewer.js"), "utf8");
  assert.match(viewer, /from "\.\/neuroglancer\/neuroglancer\.js"/);

  // Only the public API surface.
  for (const symbol of ["setupDefaultViewer", "StatusMessage"]) {
    assert.ok(viewer.includes(symbol), `${symbol} should be imported`);
  }
  // The required capabilities are all present.
  for (const method of [
    "mount(", "dispose(", "setLayers(", "updateLayers(",
    "setLayerVisibility(", "getPosition(", "onStateChanged(",
    "onPositionChanged(",
  ]) {
    assert.ok(viewer.includes(method), `viewer.js should expose ${method}`);
  }
  assert.match(viewer, /export function withTransform/);
});

test("applying a state keeps the camera, so updates do not reload", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // restoreState on the live viewer, not a fresh mount.
  assert.match(viewer, /viewer\.state\.restoreState\(state\)/);

  // The camera survives because `restoreState` only touches the keys it is
  // given - not because they are copied over. Resetting first would send the
  // camera to the origin, and nothing brings it back when the layer URLs are
  // unchanged, which is what made a transform-key switch render nothing.
  const setState = viewer.slice(
    viewer.indexOf("setState(state, {"),
    viewer.indexOf("// Layers"),
  );
  assert.ok(
    /if \(!preserveView\) viewer\.state\.reset\(\)/.test(setState),
    "the state should only be reset when the caller gives up the view",
  );
  assert.equal(
    (setState.match(/state\.reset\(\)/g) || []).length,
    1,
    "setState should not reset the viewer on the default path",
  );
});

test("the camera is carried across a rebuilt coordinate space", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // Neuroglancer remaps the camera by dimension index when it rebuilds the
  // coordinate space from the layers; the viewer has to correct that by name.
  assert.match(viewer, /coordinateSpace\.changed\.add/);
  assert.match(viewer, /coordinateSpace\.changed\.remove/);
  assert.match(viewer, /carryCameraOver/);
});

test("a transform_key switch patches transforms instead of rebuilding layers", async () => {
  const { readFileSync } = await import("node:fs");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // Restoring a `layers` array clears the layer list and builds every layer
  // again, which loses the shader and its contrast range, the selected layer
  // and the chosen layout. When only the transforms changed, they are applied
  // to the loaded sources instead.
  assert.match(app, /setLayerTransforms\(/);
  assert.match(viewer, /setLayerTransforms\(transforms\)/);
  // The transform of a loaded source is separately watchable.
  assert.match(viewer, /loadState\.transform\.restoreState/);
  // A source that has not loaded yet gets the transform when it arrives.
  assert.match(viewer, /dataSource\.changed\.add/);
});

test("every call into Python can suspend, and they are taken one at a time", async () => {
  const { readFileSync } = await import("node:fs");
  const runtime = readFileSync(
    join(repoRoot, "docs", "browser", "py-runtime.js"), "utf8",
  );
  const session = readFileSync(
    join(repoRoot, "docs", "browser", "session-worker.js"), "utf8",
  );
  const compute = readFileSync(
    join(repoRoot, "docs", "browser", "compute-worker.js"), "utf8",
  );

  // zarr v3 has no thread to run an event loop on, so it blocks by stack
  // switching - which only works if the call into Python was made in a way
  // that permits it. A plain call raises "Cannot stack switch because the
  // Python entrypoint was a synchronous function".
  for (const entry of ["handle_json", "run_task_json", "serve_route"]) {
    assert.match(
      runtime,
      new RegExp(`${entry}\\.callPromising\\(`),
      `${entry} must be called so it can suspend`,
    );
  }

  // Suspending returns control to the event loop mid-call, so without this a
  // second message would enter Python while the first is still inside it -
  // against a session that is not written to be re-entered.
  assert.match(runtime, /let pythonTurn = Promise\.resolve\(\)/);
  for (const call of ["callCommand", "callTask", "callServe"]) {
    const start = runtime.indexOf(`function ${call}(`);
    const body = runtime.slice(start, runtime.indexOf("\n}", start));
    assert.match(body, /inTurn\(/, `${call} must take its turn`);
  }

  // And the callers have to await what is now a promise.
  assert.match(session, /await callCommand\(/);
  assert.match(session, /await callServe\(/);
  assert.match(compute, /await callTask\(/);
  assert.match(compute, /await callServe\(/);
});

test("the workers are ES modules, because Pyodide refuses classic ones", async () => {
  const { readFileSync } = await import("node:fs");
  const dir = join(repoRoot, "docs", "browser");
  const app = readFileSync(join(dir, "app.js"), "utf8");
  const runtime = readFileSync(join(dir, "py-runtime.js"), "utf8");

  // Pyodide 314 throws "Classic web workers are not supported" on start-up,
  // so the whole chain has to be modules: the Worker, the script it loads,
  // and the way that script pulls in Pyodide.
  assert.match(app, /new Worker\(url, \{ type: "module" \}\)/);
  assert.match(runtime, /await import\(\s*\/\* webpackIgnore: true \*\/ `\$\{config\.pyodide_index_url\}pyodide\.mjs`/);

  for (const worker of ["session-worker.js", "compute-worker.js", "fs-worker.js"]) {
    const source = readFileSync(join(dir, worker), "utf8");
    assert.doesNotMatch(
      source,
      /importScripts\(/,
      `${worker} must not use importScripts`,
    );
  }

  // The two Python workers take their runtime by import, and the names have
  // to be ones py-runtime actually exports.
  for (const [worker, names] of [
    ["session-worker.js", ["bootRuntime", "callCommand", "callServe"]],
    ["compute-worker.js", ["bootRuntime", "callTask", "callServe"]],
  ]) {
    const source = readFileSync(join(dir, worker), "utf8");

    // Started, not awaited. The app posts "boot" the moment it constructs the
    // Worker; a handler installed after a *top-level* await is not there yet
    // when that message arrives, and the worker then sits forever having
    // missed the only message it was sent - which is exactly what happened.
    assert.match(
      source,
      /const runtime = import\(`\.\/py-runtime\.js\$\{self\.location\.search\}`\);/,
      `${worker} must start the import without awaiting it`,
    );
    const beforeHandler = source.slice(0, source.indexOf("self.onmessage"));
    assert.doesNotMatch(
      beforeHandler,
      /\bawait\b/,
      `${worker} must install its message handler before any top-level await`,
    );

    for (const name of names) {
      assert.match(
        runtime,
        new RegExp(`export (async )?(function|let) ${name}\\b`),
        `py-runtime must export ${name} for ${worker}`,
      );
    }
  }
});

test("zarr comes from Pyodide's index, not PyPI", async () => {
  const { readFileSync } = await import("node:fs");
  const config = JSON.parse(
    readFileSync(join(repoRoot, "docs", "browser", "config.json"), "utf8"),
  );

  // Two wheels call themselves the same zarr version. Pyodide's own build
  // suspends the WebAssembly stack; PyPI's starts a thread, which the browser
  // cannot give it - every read then fails with "can't start new thread".
  assert.ok(
    config.pyodide_packages.includes("zarr"),
    "zarr must be loaded from Pyodide's package index",
  );
  assert.ok(
    !config.browser_dependencies.some((dep) => dep.startsWith("zarr")),
    "zarr must not be installed from PyPI by micropip",
  );
});

test("the Python runtime is fetched once, not once per worker", async () => {
  const { readFileSync } = await import("node:fs");
  const sw = readFileSync(join(repoRoot, "docs", "browser", "sw.js"), "utf8");

  // Every worker installs the same ~60 MB runtime and they boot together, so
  // without a cache and single-flight the same bytes are fetched once per
  // worker.
  assert.match(sw, /RUNTIME_CACHE/);
  assert.match(sw, /inFlight/);
  assert.match(sw, /caches\.open\(RUNTIME_CACHE\)/);
  // Cross-origin runtime assets are intercepted; everything else is not.
  assert.match(sw, /RUNTIME_ASSET\.test\(url\.pathname\)/);
  assert.match(sw, /url\.origin !== self\.location\.origin/);

  // itk-wasm ships its pipelines zstd-compressed, so elastix arrives as
  // `elastix.wasm.zst` - a 2.4 MB file every registering worker asks for.
  const pattern = new RegExp(
    sw.match(/const RUNTIME_ASSET = (\/.*\/);/)[1].slice(1, -1),
  );
  assert.ok(pattern.test("/npm/@itk-wasm/elastix/dist/pipelines/elastix.wasm.zst"));
  assert.ok(pattern.test("/pyodide/v314.0.4/full/numpy.whl"));
  assert.ok(!pattern.test("/some/image.png"));
});

test("the shipped pyodide lockfile drops the dependency nothing imports", async () => {
  const { readFileSync, existsSync } = await import("node:fs");
  const lockPath = join(
    repoRoot, "docs", "browser", "packages", "pyodide-lock.json",
  );
  if (!existsSync(lockPath)) return; // built artifact; absent in a fresh clone

  const lock = JSON.parse(readFileSync(lockPath, "utf8"));
  // Pyodide declares matplotlib a dependency of networkx, which drags ~10 MB
  // of it and its font stack into every worker for a module nothing calls.
  assert.ok(lock.packages.networkx, "networkx should be in the lockfile");
  assert.ok(
    !lock.packages.networkx.depends.includes("matplotlib"),
    "matplotlib should not be pulled in via networkx",
  );
  // Only the dependency graph is trimmed; packages themselves are untouched.
  assert.ok(lock.packages.matplotlib, "matplotlib itself should still exist");
  assert.ok(Object.keys(lock.packages).length > 100);
});

test("a custom pyodide lockfile is loaded with an explicit package base", async () => {
  const { readFileSync } = await import("node:fs");
  const runtime = readFileSync(
    join(repoRoot, "docs", "browser", "py-runtime.js"), "utf8",
  );

  // Pyodide defaults `packageBaseUrl` to the directory the lockfile came
  // from. Ours is served from `packages/`, so without an explicit base every
  // wheel is looked for there - producing a wall of SRI failures and a
  // runtime with no micropip, nowhere near the lockfile that caused it.
  if (runtime.includes("lockFileURL")) {
    assert.match(
      runtime,
      /packageBaseUrl:\s*config\.pyodide_index_url/,
      "lockFileURL must be accompanied by packageBaseUrl",
    );
  }
});

test("layers are addressed by the URL they read, not by their name", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  // Neuroglancer renames layers it opens: an OME-Zarr carrying omero metadata
  // turns "0: tile.ome.zarr" into "0: tile.ome.zarr channel 0". A lookup by
  // name then misses, the in-place update throws, and the app falls back to
  // applying the whole state - resetting the layout and refetching the data.
  // The source URL is the app's own handle and survives the rename.
  assert.match(viewer, /dataSource\.spec\?\.url === url/);
  assert.match(app, /transforms\[url\]/);
  assert.match(app, /visibility\[url\]/);

  // The name must not be what either side matches on.
  const patchPath = viewer.slice(
    viewer.indexOf("setLayerTransforms(transforms)"),
    viewer.indexOf("updateLayers(patches)"),
  );
  assert.ok(
    !/wanted\.has\(managed\.name\)|\.get\(managed\.name\)/.test(patchPath),
    "setLayerTransforms must not look layers up by name",
  );
});

test("clearing gives a genuinely fresh viewer", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  const reset = viewer.slice(viewer.indexOf("  reset() {"));

  // Emptying the layer list is not enough: Neuroglancer keeps the combined
  // coordinate space, so the next dataset is measured in the previous one's
  // dimensions and bounds. The viewer is rebuilt instead.
  assert.match(reset, /this\.dispose\(\);/);
  assert.match(reset, /this\.mount\(target\);/);

  // A new instance restores from the URL fragment on the way up, which would
  // bring the discarded dataset straight back.
  assert.match(reset, /location\??\.hash/);
  assert.match(reset, /replaceState/);

  // The page resets on clear, and when a load has nothing in common with
  // what is on screen.
  assert.match(app, /if \(viewer\.mounted\) viewer\.reset\(\);/);
  assert.match(app, /!wanted\.some\(\(url\) => known\.includes\(url\)\)/);
  assert.match(app, /viewer\.reset\(\);\n\s*state\.layerSources = sources;/);
});

test("adding the fused preview leaves the rest of the viewer alone", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  // Restoring a `layers` array clears the layer list and rebuilds every
  // layer, replacing the chosen layout, the selected layer and each layer's
  // shader and contrast range. A layer that appears or disappears is applied
  // on its own instead.
  assert.match(viewer, /addLayers\(specs\)/);
  assert.match(viewer, /removeLayers\(urls\)/);
  assert.match(viewer, /makeLayer\(viewer\.layerSpecification, spec\.name, spec\)/);
  assert.match(viewer, /layerManager\.removeManagedLayer\(managed\)/);

  assert.match(app, /viewer\.removeLayers\(removed\)/);
  assert.match(app, /viewer\.addLayers\(added\)/);

  // A layer added a moment ago has no loaded source to re-aim yet, so only
  // the ones that were already there are patched.
  assert.match(app, /known\.includes\(url\)/);
});

test("the browser chrome exposes the complete responsive workflow", () => {
  const html = readFileSync(
    join(repoRoot, "docs", "browser", "index.html"),
    "utf8",
  );
  const css = readFileSync(
    join(repoRoot, "docs", "browser", "app.css"),
    "utf8",
  );
  const app = readFileSync(
    join(repoRoot, "docs", "browser", "app.js"),
    "utf8",
  );

  for (const id of [
    "data-panel",
    "viewer",
    "operations-panel",
    "channel-controls",
    "empty-channels",
    "positional-colors",
    "example-menu",
    "placement-panel",
    "registration-panel",
    "registration-pairwise",
    "registration-common",
    "registration-all-layers",
    "registration-selected-layers",
    "registration-advanced",
    "registration-graph",
    "registration-resolution-level",
    "registration-method",
    "registration-pruning-method",
    "registration-max-angle",
    "registration-pair-first",
    "registration-pair-second",
    "registration-add-pair",
    "registration-pair-list",
    "registration-groupwise",
    "registration-groupwise-transform",
    "registration-reference-view",
    "fusion-panel",
    "output-chunksizes",
    "log-dialog",
    "viewer-help-dialog",
    "about-dialog",
  ]) {
    assert.match(html, new RegExp(`id="${id}"`));
  }
  assert.match(
    html,
    /id="worker-count"[^>]*type="number"[^>]*value="3"/,
  );
  assert.match(html, /href="https:\/\/github\.com\/multiview-stitcher\/multiview-stitcher"/);
  assert.match(html, /Registration &amp; Fusion in the browser \(OME-Zarr\)/);
  assert.match(html, /Hold <kbd>Ctrl<\/kbd> and scroll/);
  assert.match(html, /Maximum angle \(degrees\)/);
  assert.match(html, /id="registration-max-angle"[^>]*step="1"/);
  assert.match(css, /\.channel-contrast-line/);
  assert.match(app, /range\.className = "dual-range"/);
  assert.match(app, /pre_reg_pruning_method_kwargs: pruningKwargs/);
  assert.match(app, /pairs: manualPairs \? selectedRegistrationPairs\(\) : null/);
  assert.match(app, /groupwise_resolution_kwargs: groupwiseResolutionKwargs/);
  assert.match(app, /view_indices: registrationViewIndices\(\)/);
  assert.match(app, /function registrationEligibleViews\(described = state\.session\)/);
  assert.match(app, /selectedOnly \|\| state\.selectedViewUrls\.has\(view\.url\)/);
  assert.match(app, /syncRegistrationScopedOptions\(\)/);
  assert.match(app, /maxAngleDegrees \* Math\.PI\) \/ 180/);
  assert.doesNotMatch(app, /for \(let second = first \+ 1/);
  assert.match(css, /@media \(max-width: 820px\)/);
  assert.match(css, /grid-template-areas:\s*"viewer"\s*"data"\s*"operations"/);
});

test("channel and contrast controls update loaded layers in place", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  assert.match(viewer, /setDisplayVisibility\(visibility, channelVisibility/);
  assert.match(viewer, /channelVisibility\[layerChannel\] !== false/);
  assert.match(viewer, /managed\.setVisible\(Boolean\(visibility\[url\]\) && channelVisible\)/);
  assert.match(viewer, /setContrastLimits\(visibility, channelIndex, limits\)/);
  assert.match(viewer, /range,/);

  const channelHandler = app.slice(
    app.indexOf("function renderChannelControls"),
    app.indexOf("function renderViews"),
  );
  assert.doesNotMatch(channelHandler, /refreshViewer/);
  assert.match(channelHandler, /applyDisplayVisibility/);
  assert.match(channelHandler, /applyContrastLimits/);
  assert.match(channelHandler, /visibility\.addEventListener\("change"/);
  assert.match(channelHandler, /slider\.addEventListener\("input"/);
  assert.match(app, /output_chunksize: dimensionValues\("#output-chunksizes"/);

  assert.match(viewer, /setupDefaultViewer\(\{\s*target,/);
  assert.match(viewer, /showToolPaletteButton: false/);
  assert.doesNotMatch(viewer, /showLayerListPanelButton: false/);
  assert.doesNotMatch(viewer, /showLayerSidePanelButton: false/);
  assert.match(viewer, /this\.#viewer\.selectedLayer\.visible = false/);
  assert.match(viewer, /this\.#viewer\.layerListPanelState\.location\.visible = false/);
  assert.match(viewer, /setPositionalColors\(colors = null\)/);
  assert.match(viewer, /POSITIONAL_COLOR_SHADER/);
  assert.match(app, /command\("positional_colors"/);
  assert.match(app, /className = "derived-view"/);
});

test("the tool palette Neuroglancer opens by itself is closed again", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // `showToolPaletteButton: false` removes the button that opens a palette,
  // but Neuroglancer adds a "Shader controls" palette on its own whenever a
  // multi-channel image finishes loading - which is every dataset this app
  // opens. Only closing it as it is registered keeps it off the screen.
  assert.match(viewer, /toolPalettes\.changedShallow\.add/);
  assert.match(viewer, /toolPalettes\.changedShallow\.remove/);
  assert.match(viewer, /palette\.location\.visible = false/);

  // Closed, not deleted: Neuroglancer only adds the palette when none with
  // that query exists, so a deleted one comes straight back with the next
  // multi-channel layer.
  assert.doesNotMatch(viewer, /palette\.dispose\(\)/);
  assert.doesNotMatch(viewer, /toolPalettes\.reset\(\)/);
});

test("the horizontal layer bar is off, and its contents still reachable", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // Neuroglancer's layer bar lists the layers across the top of the viewer,
  // which the app's own layers list already does - on a row that grows with
  // the number of tiles, taking the height from the data.
  assert.match(viewer, /showLayerPanel: false/);

  // The button that opens the layer list panel is what keeps every layer's
  // own controls reachable once the bar is gone, so it must stay in the top
  // row. Only the panel itself is closed, and only to begin with.
  assert.doesNotMatch(viewer, /showLayerListPanelButton: false/);
  assert.match(viewer, /layerListPanelState\.location\.visible = false/);
});

test("tiles are dragged in the cross-sections only, and never through a slice", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // Bound on the app's own slice-view map. That map has Neuroglancer's
  // defaults as a parent at the lowest priority, so this wins over the
  // `annotate` it ships with - and the perspective panel, which has a
  // separate map, never sees it. A drag across a projection does not name a
  // position in the volume, so it must not start one.
  assert.match(viewer, /inputEventBindings\.sliceView\.set\(/);
  assert.doesNotMatch(viewer, /inputEventBindings\.perspectiveView/);
  // Modifiers are matched exactly, so each gesture needs its own binding.
  // Alt, not control: control picks layers by clicking, and one modifier
  // meaning two things is how a click ends up moving a tile.
  const moveEvents = viewer.slice(
    viewer.indexOf("const MOVE_LAYER_EVENTS"),
    viewer.indexOf("const PICK_LAYER_ACTION"),
  );
  assert.match(moveEvents, /"at:alt\+mousedown0"/);
  assert.match(moveEvents, /"at:control\+alt\+mousedown0"/);
  assert.doesNotMatch(moveEvents, /"at:control\+mousedown0"/);
  // Removed again when placement is off, which restores the default binding
  // rather than leaving the gesture dead.
  assert.match(viewer, /inputEventBindings\.sliceView\.delete\(/);
  // Second guard, for the panel the pointer is actually over: a panel without
  // a slice view is the perspective one.
  assert.match(viewer, /if \(!panel\.sliceView\) continue/);

  // The drag is converted through the panel's own viewport, which is already
  // in the plane of that cross-section.
  assert.match(viewer, /translateDataPointByViewportPixels\(/);
});

test("a rotation turns a tile about its own centre, in physical units", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // Both gestures carry alt, so shift is what separates them; they share the
  // target-picking path up to that point.
  assert.match(viewer, /event\.ctrlKey \? "rotate" : "translate"/);

  // Display coordinates are voxels, and voxels are not cubes: rotating voxel
  // counts is a shear. The plane basis is converted before any of the
  // trigonometry happens, and measured over a long step, since Neuroglancer
  // projects through float32 and one pixel there is mostly rounding.
  assert.match(viewer, /toPhysical\(\s*this\.#displayDelta\(drag, dx \* BASIS_SPAN/);

  // The centre is the tile's own, captured once. A tile's bounds move with
  // it, so a centre recomputed each frame would chase its own tail.
  assert.match(viewer, /centre: tileCentre\(outputSpace\)/);

  // A Neuroglancer matrix mixes units - physical linear coefficients, a
  // translation in output pixels - and that mixture does not survive a matrix
  // product. Composing without converting drags the centre of the turn off
  // the tile, by the ratio of the two spacings: invisible in an xy view.
  assert.match(
    viewer,
    /composeAffine\(\s*turn,\s*toPhysicalMatrix\(base\.matrix, rank, base\.outputScales\),/,
  );
  assert.match(viewer, /fromPhysicalMatrix\(/);
});

test("a drag moves loaded sources in place, from a fixed starting matrix", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  // Assigning the transform of a *loaded* source is what moves the data
  // without rebuilding the layer, its shader or its contrast range - the same
  // reason `setLayerTransforms` exists.
  assert.match(viewer, /transform\.transform = translateMatrix\(/);
  // Every source reading that URL: a multi-channel tile is several layers and
  // has to move as one.
  assert.match(viewer, /this\.#sourcesReading\(url\)/);
  // Recomputed from the matrix captured at mousedown, so a long drag cannot
  // accumulate rounding into a drift.
  assert.match(viewer, /matrix: Float64Array\.from\(/);

  // The transform key is written once, when the drag ends. Every frame of a
  // drag reaches the app as a state change, and saving each one would retire
  // the fused preview over and over.
  assert.match(viewer, /get dragging\(\)/);
  assert.match(app, /if \(viewer\.dragging\) return;/);
  assert.match(
    app,
    /onDragEnd:[\s\S]{0,80}schedulePlacementSync\(viewer\.getState\(\), \{ fromDrag: true \}\)/,
  );
});

test("manual placement writes whichever coordinate system is displayed", async () => {
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  assert.match(html, /id="manual-placement"/);
  assert.match(html, /id="manual-placement-target"/);
  assert.match(html, /<kbd>Ctrl<\/kbd> \+ <kbd>Alt<\/kbd> \+ drag/);

  // Any transform key, not only one "Create transform" made: the drag names
  // the coordinate system by being made while it is on screen. The panel says
  // which that is, since the drag will rewrite it.
  const sync = app.slice(
    app.indexOf("function syncManualPlacement"),
    app.indexOf("function renderViews"),
  );
  assert.doesNotMatch(sync, /editableTransformKeys/);
  assert.match(sync, /checkbox\.disabled = !possible/);
  assert.match(app, /Drags are saved into/);

  // An edit made through Neuroglancer's own source tab has no such moment to
  // point at, so that path is still confined to the keys created here.
  assert.match(
    app,
    /!fromDrag && !state\.editableTransformKeys\.has\(transformKey\)/,
  );

  // Input views only. A fused image is derived from where the tiles are, so
  // dragging it would describe nothing the session could save.
  assert.match(sync, /state\.currentViewLayerUrls/);
  assert.doesNotMatch(sync, /currentFusedLayerUrls/);
});

test("a placement can be restricted to some channels and timepoints", async () => {
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  assert.match(html, /id="placement-channels"/);
  assert.match(html, /id="placement-time-first"/);
  assert.match(html, /id="placement-time-last"/);

  // Null, not "all of them": it is what lets the session store one affine for
  // the whole image instead of one per channel, so the parameters stay free
  // of an axis they would not vary over.
  const scope = app.slice(
    app.indexOf("function placementChannels"),
    app.indexOf("function renderPlacementScope"),
  );
  assert.match(scope, /chosen\.length === channels\.length\s*\?\s*null/);
  assert.match(scope, /first === 0 && last === count - 1 \? null/);

  // The drag itself shows the channel restriction - the viewer opens one
  // layer per channel, each with its own transform.
  assert.match(app, /channels: placementChannels\(\)/);
  assert.match(viewer, /#sourcesReading\(url, placement\.channels\)/);
  assert.match(viewer, /if \(channel !== null && !channels\.has\(channel\)\)/);

  // Both restrictions reach the session with the placement they were made
  // under, rather than whatever the checkboxes say when the save runs.
  assert.match(app, /const channels = fromDrag \? placementChannels\(\) : null/);
  assert.match(app, /time_range: timeRange/);
});

test("a placement can be pinned to the timepoint on screen", async () => {
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  assert.match(html, /name="placement-time-mode" value="current"/);
  // A range over every timepoint is what a session starts with, so it is the
  // checked one: an option nobody opens must place tiles as it always did.
  assert.match(html, /name="placement-time-mode" value="range" checked/);

  // Read when the drag is saved rather than when the option was chosen - the
  // timepoint that counts is the one the tile was moved at. `placementTimeRange`
  // is called from the save, so reading `state.timeIndex` there is what makes
  // scrubbing and then dragging place the tile where the drag was seen.
  const range = app.slice(
    app.indexOf("function placementTimeRange()"),
    app.indexOf("function renderPlacementScope"),
  );
  assert.match(range, /placementTimeMode\(\) === "current"/);
  assert.match(range, /return \[index, index\]/);

  // A range slider that no longer says anything does not stay on screen, and
  // the heading follows the viewer while it is the timepoint being named.
  assert.match(app, /row\.hidden = times\.length < 2 \|\| current/);
  const follow = app.slice(
    app.indexOf("function noteTimeIndex()"),
    app.indexOf("/** The layers a state describes"),
  );
  assert.match(follow, /updatePlacementTimeUi\(\)/);
});

test("a transform that varies over time or channel is shown as one sample", async () => {
  const { readFileSync } = await import("node:fs");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // A source transform is one matrix. Over time that means showing the
  // timepoint being viewed, and re-aiming the layers when it moves.
  assert.match(app, /time_index: state\.timeIndex/);
  assert.match(app, /function noteTimeIndex\(\)/);
  assert.match(app, /if \(!state\.timeVaryingTransforms\) return;/);

  // Re-aiming, not rebuilding: a scrub changes which sample of each transform
  // a layer carries and nothing else, so asking for a whole viewer state on
  // every step would take apart every layer, shader and contrast range to say
  // the same thing.
  const follow = app.slice(
    app.indexOf("function noteTimeIndex()"),
    app.indexOf("/** The layers a state describes"),
  );
  assert.match(follow, /refreshTransforms\(\)/);
  assert.ok(
    !/refreshViewer\(\)/.test(follow),
    "following the timepoint must not rebuild the viewer state",
  );
  assert.match(app, /command\("view_transforms"/);
  assert.match(app, /viewer\.setLayerTransforms\(transforms\)/);
  // A drag can only show one timepoint of a placement stored for a range of
  // them, so what the session holds is what ends up on screen.
  assert.match(app, /if \(hadPreview \|\| timeRange\)/);

  // Over channel it means one layer each, aimed separately - which cannot
  // travel inside the state, since the state has one layer per view.
  assert.match(app, /command\("channel_transforms"/);
  assert.match(viewer, /setChannelTransforms\(transforms\)/);

  // Registering a timelapse resolves one transform per timepoint just like a
  // time-scoped manual placement does, so it has to flip the same flag -
  // otherwise the viewer keeps showing the sample it was built with as the
  // user scrubs time, and a registered timelapse looks unregistered past
  // frame zero.
  const register = app.slice(
    app.indexOf("async function doRegister"),
    app.indexOf("async function doFusePreview"),
  );
  assert.match(
    register,
    /if \(timeCoords\(\)\.length > 1\) state\.timeVaryingTransforms = true;/,
  );
});

test("views can be selected in the list, which is what a drag acts on", async () => {
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");
  const css = readFileSync(join(repoRoot, "docs", "browser", "app.css"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  assert.match(app, /function selectView\(url, \{ extend = false \} = \{\}\)/);
  assert.match(app, /state\.selectedViewUrls/);
  assert.match(app, /aria-selected/);
  // The row is the target, minus the controls it already carries.
  assert.match(app, /event\.target\.closest\("input, button"\)/);
  assert.match(css, /\.view-list li\.selected/);

  // Ctrl-click builds a set; a button takes all of them or none.
  assert.match(app, /extend: event\.ctrlKey \|\| event\.metaKey/);
  assert.match(html, /id="toggle-selection"/);
  assert.match(app, /function toggleAllSelected\(\)/);

  // The tiles a drag acts on are chosen in the views list, on the other side
  // of the window from the placement panel - so the panel says so, and says
  // what the selection currently amounts to.
  assert.match(html, /id="placement-tiles-label"/);
  assert.match(html, /Ctrl\+click \(&#8984; on macOS\) either one/);
  assert.match(app, /\$\("#placement-tiles-label"\)\.textContent/);

  // The whole selection reaches the viewer, which is the only thing it is
  // for, and several of them move together.
  assert.match(app, /selectedUrls: \[\.\.\.state\.selectedViewUrls\]/);
  assert.match(viewer, /pickDragTarget\(under, placement\.selectedUrls\)/);
  // Each tile turns about its own centre; only the angle is shared, and it is
  // measured around the tile the pointer actually grabbed.
  assert.match(viewer, /const anchor = urls\.find\(\(url\) => under\.includes\(url\)\)/);
  assert.match(viewer, /centre: base\.centre/);
});

test("a layer is highlighted at the same weight on both sides of the window", async () => {
  const { readFileSync } = await import("node:fs");
  const css = readFileSync(join(repoRoot, "docs", "browser", "app.css"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  // Two strengths, and the same two in each half: pointed at is the very
  // subtle one, picked is the subtle one.
  assert.match(css, /\.view-list li\.highlighted/);
  assert.match(css, /\.mvs-layer-highlight \{/);
  assert.match(css, /\.mvs-layer-highlight\.subtle/);
  assert.match(app, /subtle: \[\.\.\.state\.selectedViewUrls\]\.flatMap\(shownLayerUrlsOf\)/);
  assert.match(app, /verySubtle: state\.hoveredViewUrl/);

  // One field for what is pointed at, written from either side. The list and
  // the viewer are two views of it, not two states that have to be reconciled.
  assert.match(app, /function noteHoveredView\(url\)/);
  assert.match(
    app,
    /addEventListener\("pointerenter", \(\) => noteHoveredView\(view\.url\)\)/,
  );
  assert.match(app, /onHover: \(layerUrl\) =>/);

  // The outline is drawn over the canvas and must not swallow the clicks and
  // drags meant for what is underneath it.
  assert.match(css, /\.mvs-layer-highlights \{[^}]*pointer-events: none/);
});

test("an outline is the layer's own edges, and so is the hit test", async () => {
  const { readFileSync } = await import("node:fs");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // The output space's bounds are the upright box around a placed layer, so
  // they cannot describe a turned tile - they are the box it is inscribed in.
  // The source box is the tile and the matrix is how it is placed, so the two
  // together are what an outline has to be drawn from.
  assert.match(viewer, /sourceLower: transform\.inputSpace\.bounds\.lowerBounds/);
  assert.match(viewer, /matrix: transform\.transform/);

  // Both the outline and "which layer is under the pointer" come from one
  // call. Two readings of the same placement is how a highlight ends up around
  // a tile the pointer is not on, in exactly the corners a rotation creates.
  const geometry = viewer.slice(viewer.indexOf("  #layerGeometry(url"));
  assert.match(viewer, /layerSlabs\(\s*layer,/);
  assert.match(viewer, /containsPoint\(geometry, point\)/);
  assert.match(geometry, /layerGeometry\(placementOf\(transform\), rows\)/);

  // Both spacings are needed, and for different parts of the matrix: the
  // linear coefficients act on physical coordinates and so are scaled by the
  // *source* dimension each consumes, while the translation lands in output
  // indices. Reading either with the other's spacing shears every layer whose
  // rotation mixes two axes that are not spaced alike.
  assert.match(viewer, /sourceScales: transform\.inputSpace\.scales/);
  assert.match(viewer, /outputScales: transform\.outputSpace\.scales/);
});

test("a hidden layer takes no part in pointing, picking or placing", async () => {
  const { readFileSync } = await import("node:fs");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  // One helper decides it, so the outline, the hover, the click and the drag
  // cannot end up disagreeing about whether a layer is there.
  assert.match(app, /function shownLayerUrlsOf\(viewUrl\)/);
  assert.match(app, /state\.viewVisibility\.get\(viewUrl\) === false \? \[\]/);

  const uses = app.match(/shownLayerUrlsOf/g) || [];
  assert.ok(uses.length >= 5, `expected every list to use it, saw ${uses.length}`);
  assert.match(app, /subtle: \[\.\.\.state\.selectedViewUrls\]\.flatMap\(shownLayerUrlsOf\)/);
  assert.match(app, /movableUrls: \[\.\.\.state\.currentViewLayerUrls\.keys\(\)\]\.flatMap\(\s*shownLayerUrlsOf,?\s*\)/);

  // And a change of visibility has to be said again, or the outline of a
  // layer that has just been hidden stays where it was.
  const visibility = app.slice(
    app.indexOf("function applyDisplayVisibility"),
    app.indexOf("async function applyPositionalColors"),
  );
  assert.match(visibility, /syncManualPlacement\(\)/);
});

test("clicking a tile in the viewer selects it, exactly as its row does", async () => {
  const { readFileSync } = await import("node:fs");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  // The same call the list makes, so the two cannot drift apart - ctrl / cmd
  // included.
  assert.match(app, /if \(viewUrl\) selectView\(viewUrl, \{ extend \}\)/);
  assert.match(viewer, /extend: event\.ctrlKey \|\| event\.metaKey/);

  // Only when the pointer names one layer. Where tiles overlap it names none,
  // and picking one anyway would be a guess the views list does not have to
  // make.
  assert.match(viewer, /under\.length === 1/);

  // A press that travelled is a pan, not a pick: plain drag is how the camera
  // moves, so without this every pan would end in a selection.
  assert.match(viewer, /CLICK_SLOP_PX/);
  assert.match(viewer, /Math\.hypot\(event\.clientX - press\.x/);

  // Pointer events rather than mouse events: Neuroglancer claims `mousedown`
  // in the cross-sections and stops it there.
  assert.match(viewer, /addEventListener\("pointerdown", this\.#onPointerDown/);
  assert.doesNotMatch(viewer, /addEventListener\("mousedown"/);
});

test("a time axis gets a slider over the viewer's own position", async () => {
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");
  const viewer = readFileSync(join(repoRoot, "docs", "browser", "viewer.js"), "utf8");

  assert.match(html, /id="time-slider"/);
  assert.match(app, /function renderTimeSlider\(\)/);
  // Hidden rather than disabled when there is nothing to scrub.
  assert.match(app, /section\.hidden = times\.length < 2/);

  // Neuroglancer has no current frame: time is one axis of the position, so
  // the slider drives that rather than keeping a copy of it. A scrub in the
  // viewer and a drag of the slider then agree by construction.
  assert.match(app, /viewer\.setTimepoint\(index\)/);
  assert.match(viewer, /setTimepoint\(index\)/);
  assert.match(viewer, /dimensions\.indexOf\("t"\)/);
});

test("views can be shown or hidden all at once, without the fused preview", async () => {
  const { readFileSync } = await import("node:fs");
  const html = readFileSync(join(repoRoot, "docs", "browser", "index.html"), "utf8");
  const app = readFileSync(join(repoRoot, "docs", "browser", "app.js"), "utf8");

  assert.match(html, /id="toggle-views"/);

  // The button walks `state.session.views` - the input views. The fused
  // preview is derived data with a toggle of its own, and hiding the inputs
  // to look at the fusion is what the button is for, so it must not be swept
  // along.
  const handler = app.slice(
    app.indexOf('$("#toggle-views").addEventListener'),
    app.indexOf('$("#transform-key").addEventListener'),
  );
  assert.match(handler, /state\.session\?\.views \|\| \[\]/);
  assert.match(handler, /state\.viewVisibility\.set\(view\.url, visible\)/);
  assert.doesNotMatch(handler, /previewVisibility|currentFusedLayerUrls/);
  assert.match(handler, /applyDisplayVisibility\(\)/);
});

test("a mounted CZI is readable by every Python worker", async () => {
  const { readFileSync } = await import("node:fs");
  const read = (name) =>
    readFileSync(join(repoRoot, "docs", "browser", name), "utf8");

  const runtime = read("py-runtime.js");

  // WORKERFS is the only mount that reads a File lazily: it slices the Blob
  // and reads it with FileReaderSync, so a multi-gigabyte CZI is seeked
  // through rather than copied into the WebAssembly heap. NATIVEFS_ASYNC or
  // writing the bytes into MEMFS would both load the whole file.
  assert.match(runtime, /filesystems\.WORKERFS/);
  assert.match(runtime, /export function mountFiles/);

  // Python opens the file wherever the work runs. A compute worker rebuilds a
  // session from source URLs alone, so it needs the same mount as the session
  // worker or every chunk of a CZI view fails to open.
  for (const name of ["session-worker.js", "compute-worker.js"]) {
    assert.match(read(name), /mount-files/, `${name} must accept mounts`);
  }

  const app = read("app.js");
  assert.match(app, /type: "mount-files"/);
  // Workers started after the file was mounted have to be caught up, which is
  // what `state.fileMounts` is kept for.
  assert.match(app, /state\.fileMounts/);
});

test("elastix is offered as a registration method, with its options", async () => {
  const { readFileSync } = await import("node:fs");
  const dir = join(repoRoot, "docs", "browser");
  const html = readFileSync(join(dir, "index.html"), "utf8");
  const app = readFileSync(join(dir, "app.js"), "utf8");
  const config = JSON.parse(readFileSync(join(dir, "config.json"), "utf8"));

  // Three small pure-Python wheels; the WebAssembly pipeline behind them is
  // fetched from a CDN the first time a worker registers with elastix, so
  // naming it here costs a boot nothing but makes the method selectable.
  assert.match(config.browser_dependencies.join(" "), /itkwasm-elastix/);

  for (const id of [
    "registration-method",
    "registration-elastix-options",
    "registration-elastix-transform",
    "registration-elastix-resolutions",
    "registration-elastix-iterations",
    "registration-elastix-metric",
  ]) {
    assert.match(html, new RegExp(`id="${id}"`));
  }

  // The value has to be a key of specs.PAIRWISE_REGISTRATION_FUNCS: Python
  // rejects anything else, and it is the only thing that names the function.
  assert.match(html, /<option value="itk_elastix"/);

  const register = app.slice(
    app.indexOf("async function doRegister"),
    app.indexOf("async function doFusePreview"),
  );
  assert.match(register, /pairwise_reg_func: method/);
  assert.match(
    register,
    /method === "itk_elastix" \? elastixRegistrationKwargs\(\) : \{\}/,
  );

  // A translation stage runs before the chosen transform, and the groupwise
  // resolution is kept at the same transform type - resolving rigid pairwise
  // results into translations would throw the rotations away again.
  assert.match(
    app,
    /transform === "translation" \? \[transform\] : \["translation", transform\]/,
  );
  assert.match(app, /function syncElastixTransform\(\)/);
  assert.match(app, /\$\("#registration-groupwise-transform"\)\.value = \$\(/);
});

test("CZI reading is installable in Pyodide", async () => {
  const { readFileSync } = await import("node:fs");
  const config = JSON.parse(
    readFileSync(join(repoRoot, "docs", "browser", "config.json"), "utf8"),
  );

  // Both are pure-Python wheels; czifile reads through tifffile's FileHandle.
  const dependencies = config.browser_dependencies.join(" ");
  assert.match(dependencies, /czifile/);
  assert.match(dependencies, /tifffile/);

  // imagecodecs is a C extension with no WebAssembly build. czifile 2019.7.2.3
  // treats it as optional and reads uncompressed CZI without it; the 2026
  // releases import it unconditionally and would not load at all.
  assert.ok(
    config.browser_dependencies.includes("czifile==2019.7.2.3"),
    "czifile must be pinned to the release that makes imagecodecs optional",
  );
  assert.ok(
    !dependencies.includes("imagecodecs"),
    "imagecodecs cannot be installed in Pyodide",
  );
});
